//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chweb.Launch.IpcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IpcServiceReference.IIpcService")]
    public interface IIpcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIpcService/ShowChooser", ReplyAction="http://tempuri.org/IIpcService/ShowChooserResponse")]
        void ShowChooser(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IIpcServiceChannel : Chweb.Launch.IpcServiceReference.IIpcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class IpcServiceClient : System.ServiceModel.ClientBase<Chweb.Launch.IpcServiceReference.IIpcService>, Chweb.Launch.IpcServiceReference.IIpcService {
        
        public IpcServiceClient() {
        }
        
        public IpcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IpcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ShowChooser(string url) {
            base.Channel.ShowChooser(url);
        }
    }
}
